#!/usr/bin/env bash
# /app/setup.sh
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

export CI=1
export DEBIAN_FRONTEND=noninteractive
export PIP_NO_INPUT=1
export PIP_DISABLE_PIP_VERSION_CHECK=1
export npm_config_audit=false
export npm_config_fund=false
export npm_config_update_notifier=false

# Toggles:
# - FULL_ACCESS=1  -> dump (almost) all env vars into .env (created only if missing)
# - SETUP_STRICT=1 -> fail if migrations/build fail (default: warn and continue)
# - FORCE_RESCAN=1 -> regenerate setup.env.keys even if it exists
FULL_ACCESS="${FULL_ACCESS:-0}"
SETUP_STRICT="${SETUP_STRICT:-0}"
FORCE_RESCAN="${FORCE_RESCAN:-0}"

log()  { printf "\n\033[1m==> %s\033[0m\n" "$*"; }
warn() { printf "\033[33m[warn]\033[0m %s\n" "$*" >&2; }
die()  { printf "\033[31m[error]\033[0m %s\n" "$*" >&2; exit 1; }
has()  { command -v "$1" >/dev/null 2>&1; }

maybe_sudo() { if has sudo; then sudo -n "$@"; else "$@"; fi; }

run_quiet() { # show output only on failure
  local out
  if ! out="$("$@" 2>&1)"; then
    printf "%s\n" "$out" >&2
    return 1
  fi
}

maybe_fail() {
  local msg="$1"
  if [[ "$SETUP_STRICT" == "1" ]]; then
    die "$msg"
  else
    warn "$msg"
  fi
}

###############################################################################
# 1) System dependencies (best-effort)
###############################################################################
install_system_deps() {
  log "System deps (best-effort)"
  if has apt-get; then
    maybe_sudo apt-get update -y
    maybe_sudo apt-get install -y ca-certificates curl git jq build-essential ripgrep || warn "apt-get install failed (continuing)"
  elif has apk; then
    maybe_sudo apk add --no-interactive ca-certificates curl git jq build-base ripgrep || warn "apk add failed (continuing)"
  elif has dnf; then
    maybe_sudo dnf install -y ca-certificates curl git jq make gcc gcc-c++ ripgrep || warn "dnf install failed (continuing)"
  elif has yum; then
    maybe_sudo yum install -y ca-certificates curl git jq make gcc gcc-c++ || warn "yum install failed (continuing)"
  else
    warn "No supported system package manager found; skipping system deps"
  fi
}

###############################################################################
# 2) Generate setup.env.keys by scanning repo (if missing / forced)
###############################################################################
scan_env_keys() {
  # Output unique keys to stdout
  # Detect common patterns across JS/TS + Python (+ a few extras)
  local finder
  if has rg; then
    finder="rg"
  else
    finder="grep"
  fi

  local scan_paths=(".")
  local exclude_args=()
  if [[ "$finder" == "rg" ]]; then
    exclude_args+=(--hidden --glob '!.git/*' --glob '!node_modules/*' --glob '!.venv/*' --glob '!dist/*' --glob '!build/*' --glob '!.next/*' --glob '!coverage/*')
    # shellcheck disable=SC2086
    rg -n "${exclude_args[@]}" \
      -e 'process\.env\.([A-Z0-9_]+)' \
      -e 'import\.meta\.env\.([A-Z0-9_]+)' \
      -e 'os\.environ\.get\(\s*["'\'']([A-Z0-9_]+)["'\'']\s*\)' \
      -e 'os\.getenv\(\s*["'\'']([A-Z0-9_]+)["'\'']\s*\)' \
      -e 'Deno\.env\.get\(\s*["'\'']([A-Z0-9_]+)["'\'']\s*\)' \
      -e 'getenv\(\s*["'\'']([A-Z0-9_]+)["'\'']\s*\)' \
      "${scan_paths[@]}" 2>/dev/null \
      | sed -E 's/.*process\.env\.([A-Z0-9_]+).*/\1/; t; s/.*import\.meta\.env\.([A-Z0-9_]+).*/\1/; t; s/.*os\.environ\.get\(\s*["'\''"]([A-Z0-9_]+)["'\''"].*/\1/; t; s/.*os\.getenv\(\s*["'\''"]([A-Z0-9_]+)["'\''"].*/\1/; t; s/.*Deno\.env\.get\(\s*["'\''"]([A-Z0-9_]+)["'\''"].*/\1/; t; s/.*getenv\(\s*["'\''"]([A-Z0-9_]+)["'\''"].*/\1/' \
      | grep -E '^[A-Z0-9_]+$' \
      | sort -u
  else
    # Grep fallback (less precise but OK)
    # shellcheck disable=SC2086
    grep -RIn --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=.venv --exclude-dir=dist --exclude-dir=build --exclude-dir=.next --exclude-dir=coverage \
      -E 'process\.env\.[A-Z0-9_]+|import\.meta\.env\.[A-Z0-9_]+|os\.(environ\.get|getenv)\(\s*["'\''][A-Z0-9_]+["'\'']\s*\)|Deno\.env\.get\(\s*["'\''][A-Z0-9_]+["'\'']\s*\)|getenv\(\s*["'\''][A-Z0-9_]+["'\'']\s*\)' \
      "${scan_paths[@]}" 2>/dev/null \
      | sed -E 's/.*process\.env\.([A-Z0-9_]+).*/\1/; t; s/.*import\.meta\.env\.([A-Z0-9_]+).*/\1/; t; s/.*os\.(environ\.get|getenv)\(\s*["'\''"]([A-Z0-9_]+)["'\''"].*/\2/; t; s/.*Deno\.env\.get\(\s*["'\''"]([A-Z0-9_]+)["'\''"].*/\1/; t; s/.*getenv\(\s*["'\''"]([A-Z0-9_]+)["'\''"].*/\1/' \
      | grep -E '^[A-Z0-9_]+$' \
      | sort -u
  fi
}

generate_setup_env_keys() {
  local f="setup.env.keys"
  if [[ -f "$f" && "$FORCE_RESCAN" != "1" ]]; then
    log "setup.env.keys exists (skipping scan)"
    return 0
  fi

  log "Generating setup.env.keys by scanning repo"
  {
    echo "# Auto-generated by /app/setup.sh"
    echo "# One KEY per line. Edit freely; re-run with FORCE_RESCAN=1 to regenerate."
    scan_env_keys || true
  } > "$f"

  # Ensure a few common defaults exist
  grep -Fqx "NODE_ENV" "$f" || echo "NODE_ENV" >> "$f"
  sort -u -o "$f" "$f"
}

###############################################################################
# 3) Env files (.env created only if missing)
###############################################################################
write_env_example() {
  log "Writing .env.example (safe overwrite)"
  cat > .env.example <<'EOF'
# Copy to .env (setup.sh creates .env only if missing)
NODE_ENV=development

# Supabase
SUPABASE_URL=
SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=

# Database
DATABASE_URL=

# Redis
REDIS_URL=
EOF
}

env_escape_single_quotes() {
  # Wrap in single quotes and escape internal single quotes safely for dotenv-like usage
  # foo'bar -> 'foo'\''bar'
  local s="$1"
  s="${s//$'\n'/\\n}"
  s="${s//$'\r'/\\r}"
  s="${s//\'/\'\\\'\'}"
  printf "'%s'" "$s"
}

write_env_if_missing() {
  [[ -f .env ]] && return 0
  log "Creating .env (only if missing)"

  : > .env

  # Always write NODE_ENV
  if [[ -z "${NODE_ENV:-}" ]]; then
    printf "NODE_ENV=development\n" >> .env
  else
    printf "NODE_ENV=%s\n" "$(env_escape_single_quotes "$NODE_ENV")" >> .env
  fi

  if [[ "$FULL_ACCESS" == "1" ]]; then
    log "FULL_ACCESS=1: dumping injected env vars into .env (broad access)"

    # Denylist noisy/sensitive-to-runtime keys that often break tooling if present
    # (You can still manually add them; this is just to reduce accidental conflicts.)
    local deny_re='^(PWD|OLDPWD|SHLVL|_|\?|HOME|PATH|SHELL|TERM|USER|LOGNAME|LANG|LC_.*|SSH_.*|GIT_.*|npm_.*|NODE_OPTIONS)$'

    while IFS='=' read -r k v; do
      [[ -z "$k" ]] && continue
      [[ "$k" =~ $deny_re ]] && continue
      [[ ! "$k" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] && continue
      printf "%s=%s\n" "$k" "$(env_escape_single_quotes "$v")" >> .env
    done < <(env)

    return 0
  fi

  # Allowlisted mode (preferred)
  if [[ -f setup.env.keys ]]; then
    log "Using setup.env.keys allowlist for .env"
    while IFS= read -r k; do
      [[ -z "${k// /}" ]] && continue
      [[ "${k:0:1}" == "#" ]] && continue
      local v="${!k-}"
      [[ -z "$v" ]] && continue
      printf "%s=%s\n" "$k" "$(env_escape_single_quotes "$v")" >> .env
    done < setup.env.keys
  else
    # fallback minimal list
    local keys=(
      "SUPABASE_URL" "SUPABASE_ANON_KEY" "SUPABASE_SERVICE_ROLE_KEY"
      "NEXT_PUBLIC_SUPABASE_URL" "NEXT_PUBLIC_SUPABASE_ANON_KEY"
      "DATABASE_URL" "REDIS_URL"
    )
    for k in "${keys[@]}"; do
      local v="${!k-}"
      [[ -z "$v" ]] && continue
      printf "%s=%s\n" "$k" "$(env_escape_single_quotes "$v")" >> .env
    done
  fi
}

###############################################################################
# 4) Node deps (auto-detect pm)
###############################################################################
enable_corepack() { has corepack && run_quiet corepack enable || true; }

detect_node_pm() {
  [[ -f package.json ]] || { echo "none"; return 0; }
  if [[ -f bun.lockb || -f bun.lock ]] && has bun; then echo "bun"; return 0; fi
  if [[ -f pnpm-lock.yaml ]]; then echo "pnpm"; return 0; fi
  if [[ -f yarn.lock ]]; then echo "yarn"; return 0; fi
  echo "npm"
}

install_node_deps() {
  [[ -f package.json ]] || return 0
  local pm; pm="$(detect_node_pm)"
  log "Node deps ($pm)"

  case "$pm" in
    bun)
      run_quiet bun install --no-progress || bun install --no-progress
      ;;
    pnpm)
      enable_corepack
      if ! has pnpm && has corepack; then run_quiet corepack prepare pnpm@latest --activate || true; fi
      if has pnpm; then
        run_quiet pnpm install --frozen-lockfile || pnpm install
      else
        warn "pnpm-lock.yaml found but pnpm unavailable; falling back to npm"
        run_quiet npm ci || npm install --legacy-peer-deps || npm install
      fi
      ;;
    yarn)
      enable_corepack
      if ! has yarn && has corepack; then run_quiet corepack prepare yarn@stable --activate || true; fi
      if has yarn; then
        run_quiet yarn install --immutable || yarn install --frozen-lockfile || yarn install
      else
        warn "yarn.lock found but yarn unavailable; falling back to npm"
        run_quiet npm ci || npm install --legacy-peer-deps || npm install
      fi
      ;;
    npm)
      run_quiet npm ci || npm install --legacy-peer-deps || npm install
      ;;
    *)
      ;;
  esac
}

###############################################################################
# 5) Python deps (venv + pip/poetry)
###############################################################################
setup_python() {
  local py="python3"
  has python3 || py="python"
  if ! has "$py"; then
    warn "Python not found; skipping Python setup"
    return 0
  fi
  [[ -f requirements.txt || -f pyproject.toml ]] || return 0

  log "Python deps (.venv)"
  if [[ ! -d .venv ]]; then
    run_quiet "$py" -m venv .venv || die "Failed to create venv"
  fi
  # shellcheck disable=SC1091
  source .venv/bin/activate

  run_quiet python -m pip install -U pip setuptools wheel || true

  if [[ -f requirements.txt ]]; then
    run_quiet pip install -r requirements.txt || die "pip install -r requirements.txt failed"
  elif [[ -f pyproject.toml ]]; then
    if [[ -f poetry.lock ]]; then
      if ! has poetry; then run_quiet pip install poetry || die "Failed to install poetry"; fi
      run_quiet poetry config virtualenvs.create false --local || true
      run_quiet poetry install --no-interaction --no-ansi || die "poetry install failed"
    else
      run_quiet pip install . || die "pip install . failed"
    fi
  fi
}

###############################################################################
# 6) Supabase CLI (best-effort)
###############################################################################
supabase_project_detected() { [[ -d supabase || -f supabase/config.toml ]]; }

supabase_cmd() {
  if has supabase; then
    supabase "$@"
  elif [[ -x node_modules/.bin/supabase ]]; then
    node_modules/.bin/supabase "$@"
  elif has npx && [[ -f package.json ]]; then
    npx --yes supabase "$@"
  else
    return 127
  fi
}

ensure_supabase_cli() {
  supabase_project_detected || return 0
  supabase_cmd --version >/dev/null 2>&1 && return 0

  log "Supabase CLI (best-effort)"
  if [[ -f package.json ]] && has npm; then
    run_quiet npm install --save-dev supabase || warn "Could not install supabase locally"
  fi

  supabase_cmd --version >/dev/null 2>&1 && return 0

  if has npm; then
    run_quiet npm install -g supabase || warn "Could not install supabase globally"
  fi
}

###############################################################################
# 7) Migrations / build
###############################################################################
run_migrations() {
  log "Migrations"

  if supabase_project_detected && supabase_cmd --version >/dev/null 2>&1; then
    if ! supabase_cmd db reset --local >/dev/null 2>&1; then
      maybe_fail "Supabase db reset failed/skipped (Docker may be unavailable)"
    fi
  fi

  if [[ -f prisma/schema.prisma && -f package.json ]] && has npx; then
    npx --yes prisma generate >/dev/null 2>&1 || maybe_fail "prisma generate failed"
    npx --yes prisma migrate deploy >/dev/null 2>&1 || maybe_fail "prisma migrate deploy failed"
  fi

  if [[ -f manage.py && -d .venv ]]; then
    # shellcheck disable=SC1091
    source .venv/bin/activate
    python manage.py migrate --noinput >/dev/null 2>&1 || maybe_fail "django migrate failed"
  fi
}

run_build() {
  [[ -f package.json ]] || return 0
  has jq || { warn "jq missing; skipping build-script detection"; return 0; }

  if jq -e '.scripts.build' package.json >/dev/null 2>&1; then
    log "Build"
    if ! npm run build >/dev/null 2>&1; then
      maybe_fail "npm run build failed"
    fi
  fi
}

###############################################################################
# 8) Validation
###############################################################################
validate() {
  log "Validation"
  has node && node -v || true
  has npm && npm -v || true
  has bun && bun -v || true
  has pnpm && pnpm -v || true
  has yarn && yarn -v || true
  has python3 && python3 -V || has python && python -V || true
  supabase_cmd --version >/dev/null 2>&1 && supabase_cmd --version || true

  [[ -f .env ]] && echo ".env: present" || echo ".env: missing"
  [[ -f setup.env.keys ]] && echo "setup.env.keys: present" || echo "setup.env.keys: missing"
}

main() {
  log "=== Jules Setup Script Starting ==="
  log "Root: $ROOT_DIR"
  log "Flags: FULL_ACCESS=$FULL_ACCESS SETUP_STRICT=$SETUP_STRICT FORCE_RESCAN=$FORCE_RESCAN"

  install_system_deps

  generate_setup_env_keys
  write_env_example
  write_env_if_missing

  install_node_deps
  setup_python
  ensure_supabase_cli

  run_migrations
  run_build
  validate

  log "=== Setup Complete. Ready for Snapshot ==="
}

main "$@"
